### ISSUE TITLE
This traces can not be accessed due to the LFS quota limit

### ISSUE THREAD

**Issue by junior9203** [ikizhvatov/randomdelays-traces#1]
Hi, when i try to download the random delay traces, it occurs that "batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access." Can you reslove this problem ? 

alternative : https://help.github.com/en/github/managing-large-files/removing-files-from-git-large-file-storage

**Comment by ikizhvatov** [comment]
Should work now, I extended the quota.

**Comment by junior9203** [comment]
thanks
